language: python
python:
- 2.6
- 2.7
- pypy
install:
- pip install "pytest>=2.3.0"
script:
- python -mwand.version --verbose
- py.test
notifications:
  irc:
    channels:
    - "ircs://ssl.ozinger.org:16667#hongminhee"
    - "irc.freenode.net#wand"
    on_success: change
    on_failure: always
