language: python
python:
- 2.6
- 2.7
- pypy
install:
- pip install Attest coverage coveralls
script:
- python -mwand.version --verbose
- coverage run --source=wand -m attest.run wandtests.tests
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "ircs://ssl.ozinger.org:16667#hongminhee"
    - "irc.freenode.net#wand"
    on_success: change
    on_failure: always
