language: python
python:
- 2.6
- 2.7
- pypy
before_install:
- sudo apt-get update
- sudo apt-get install libmagickwand-dev
install:
- pip install Attest
script:
- python -mattest.run wandtests.tests
notifications:
  irc: "irc.ozinger.org#hongminhee"
