language: python
python:
- 2.6
- 2.7
- pypy
install:
- pip install pytest pytest-cov pytest-capturelog coveralls
script:
- python -mwand.version --verbose
- py.test --cov wand --durations=20
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "ircs://ssl.ozinger.org:16667#hongminhee"
    - "irc.freenode.net#wand"
    on_success: change
    on_failure: always
